# 配置文件

# 服务端配置
server:
  # 端口设置
  port: 9201

spring:
  # 配置应用信息
  application:
    # 应用名
    name: wechat-ferry
  # swagger适配
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 打成jar包必须添加如下配置才能找到页面
  thymeleaf:
    mode: HTML
    cache: false
    prefix: classpath:/templates

# 日志配置
logging:
  config: classpath:logback-spring.xml

# 本服务参数
wechat:
  ferry:
    # DLL文件位置
    dll-path: D:\project\my\WeChatFerry-JavaBot\wechat-ferry-mvn\dll\sdk.dll
    # socket端口
    socket-port: 10086
    # 需要开启消息处理的群
    open-msg-groups:
      - 52155225442@chatroom
      - 45411596543@chatroom
      - 52975427058@chatroom
      - 47530769444@chatroom
      - 48139084450@chatroom
      - 22671412275@chatroom
      - 43709931030@chatroom
      - 49010341065@chatroom
      - 48066498127@chatroom
      - 53298025926@chatroom
      - 57611285004@chatroom
      - 57770194819@chatroom
    # 接收消息转发开关
    receive-msg-fwd-switch: false
    # 接收消息转发URL
    receive-msg-fwd-urls:
      - https://api.ruojy.top/api/wx/verify
    # 发送消息转发标识 1-关闭 2-全转发 3-发送成功才转发
    send-msg-fwd-flag: '1'
    # 发送消息转发URL
    send-msg-fwd-urls:
      - http://localhost:9001/msg
    # 调用第三方服务客户端成功状态码
    third-party-ok-codes:
      # key:状态码字段 val:状态码值
      code: '200'
ruojy:
  token: MyToken
  plugin: D:\project\my\WeChatFerry-JavaBot\wechat-ferry-mvn\config\plugins
  wsUrl: ws://82.157.132.175:6099/api/ws #ws://172.16.76.240:5710/api/ws
  reConnectToServerTimeout: 30 # 尝试重连间隔时间
  overTimeout: 10 # 超时断开重试时间

plugin:
  hello:
    developerName: 小宇
